/**
 * Service worker registration with safe auto-updates.
 *
 * The service worker (generated by vite-plugin-pwa, see vite.config.ts) precaches the whole app,
 * including the Stockfish engine, so the app works offline after the first visit. A new build
 * installs in the background and takes control at once (skipWaiting + clientsClaim), but the page
 * keeps running the old code until it reloads. That reload waits until `canReloadNow()` says it
 * would not interrupt the user.
 *
 * iOS Home Screen apps resume from memory without a navigation, so the browser never looks for a
 * new service worker by itself. We check whenever the app becomes visible, when it comes back
 * online, and every hour.
 *
 * Everything here is a no-op where service workers are unavailable (node, old browsers, http://,
 * `vite dev` where the plugin provides a stub).
 */
import { registerSW } from 'virtual:pwa-register';

export interface RegisterServiceWorkerOptions {
  /**
   * Whether reloading the page right now is harmless, e.g. no game in progress and no sheet open.
   * It is polled while an update waits, so keep it cheap and free of side effects.
   */
  canReloadNow: () => boolean;
  /** Called once, when the app has been cached for offline use for the first time. */
  onOfflineReady?: () => void;
}

/** Controls the deferred reload onto a new build. */
export interface ReloadGate {
  /** A new build is active: reload now if allowed, otherwise as soon as `canReloadNow()` allows. */
  request(): void;
  /** True while a reload is waiting. */
  pending(): boolean;
  /** Reloads immediately, ignoring `canReloadNow()` (at most once). */
  reloadNow(): void;
  /** Stops waiting without reloading. */
  dispose(): void;
}

/** How often to look for a new version while the app stays open. */
const UPDATE_CHECK_INTERVAL_MS = 60 * 60 * 1000;
/** Visibility/online update checks closer together than this are skipped. */
const MIN_CHECK_GAP_MS = 60 * 1000;
/** How often `canReloadNow()` is polled while an update waits. */
const RELOAD_POLL_MS = 5 * 1000;

let registered = false;

/**
 * Registers the service worker (once) and keeps the app up to date. Call it at startup.
 * Updates are applied by reloading the page when `canReloadNow()` returns true: immediately if it
 * already does, otherwise at the next check (every few seconds and on every visibility change).
 */
export function registerServiceWorker(opts: RegisterServiceWorkerOptions): void {
  if (registered || !serviceWorkerSupported()) return;
  registered = true;

  const gate = createReloadGate(opts.canReloadNow, () => window.location.reload());
  let offlineReady = false;
  registerSW({
    immediate: true,
    // In autoUpdate mode this fires once the new service worker controls the page.
    onNeedReload: () => gate.request(),
    // The plugin also reports later updates as "offline ready" when the page started uncontrolled.
    onOfflineReady: () => {
      if (offlineReady) return;
      offlineReady = true;
      opts.onOfflineReady?.();
    },
    onRegisteredSW: (_url, reg) => {
      if (reg) watchForUpdates(reg);
    },
    onRegisterError: (err: unknown) => console.warn('[pwa] service worker registration failed', err),
  });

  // After an update the old build's lazy chunks are gone from both the server and the cache, so a
  // failing dynamic import can only be fixed by loading the new build.
  window.addEventListener('vite:preloadError', () => {
    if (gate.pending()) gate.reloadNow();
  });
}

/**
 * Deferred-reload state machine used by `registerServiceWorker` (exported for tests).
 * While pending, it re-checks `canReloadNow` every `pollMs` and on every `visibilitychange`.
 */
export function createReloadGate(
  canReloadNow: () => boolean,
  reload: () => void,
  pollMs: number = RELOAD_POLL_MS,
): ReloadGate {
  let waiting = false;
  let done = false;
  let timer: ReturnType<typeof setInterval> | undefined;
  const doc = typeof document === 'undefined' ? undefined : document;

  const stop = (): void => {
    if (timer !== undefined) clearInterval(timer);
    timer = undefined;
    doc?.removeEventListener('visibilitychange', attempt);
  };
  const reloadNow = (): void => {
    if (done) return;
    done = true;
    stop();
    reload();
  };
  function attempt(): void {
    if (!waiting || done) return;
    let ok = false;
    try {
      ok = canReloadNow();
    } catch {
      ok = false;
    }
    if (ok) reloadNow();
  }

  return {
    request() {
      if (done) return;
      if (!waiting) {
        waiting = true;
        doc?.addEventListener('visibilitychange', attempt);
        timer = setInterval(attempt, pollMs);
      }
      attempt();
    },
    pending: () => waiting && !done,
    reloadNow,
    dispose() {
      waiting = false;
      stop();
    },
  };
}

function serviceWorkerSupported(): boolean {
  return (
    typeof window !== 'undefined' &&
    typeof navigator !== 'undefined' &&
    'serviceWorker' in navigator &&
    window.isSecureContext !== false
  );
}

/** Polls for a new service worker: hourly, when the app becomes visible, and when back online. */
function watchForUpdates(reg: ServiceWorkerRegistration): void {
  let lastCheck = Date.now(); // registration itself just fetched sw.js
  const check = (force: boolean): void => {
    const now = Date.now();
    if (!force && now - lastCheck < MIN_CHECK_GAP_MS) return;
    if (navigator.onLine === false || reg.installing) return;
    lastCheck = now;
    reg.update().catch(() => {
      /* offline or a server hiccup: the next check retries */
    });
  };
  setInterval(() => check(true), UPDATE_CHECK_INTERVAL_MS);
  document.addEventListener('visibilitychange', () => {
    if (document.visibilityState === 'visible') check(false);
  });
  window.addEventListener('online', () => check(false));
}
