/**
 * Service worker registration with safe auto-updates.
 *
 * The service worker (generated by vite-plugin-pwa, see vite.config.ts) precaches the whole app,
 * including the Stockfish engine, so the app works offline after the first visit. A new build
 * installs in the background and takes control at once (skipWaiting + clientsClaim), but the page
 * keeps running the old code until it reloads. The reload waits until it cannot interrupt the user:
 * `canReloadNow()` must allow it (no game or review in progress), and the page must be hidden or
 * untouched since it was opened or brought back to the front. So a new version appears when the
 * app is launched or resumed, or while it is in the background, never under the user's finger.
 * If iOS discards the app in the background first, the next launch runs the new build anyway.
 *
 * iOS Home Screen apps resume from memory without a navigation, so the browser never looks for a
 * new service worker by itself. We check whenever the app becomes visible, when it comes back
 * online, and every hour.
 *
 * Everything here is a no-op where service workers are unavailable (node, old browsers, http://,
 * `vite dev` where the plugin provides a stub).
 */
import { registerSW } from 'virtual:pwa-register';

export interface RegisterServiceWorkerOptions {
  /**
   * Whether reloading the page would lose nothing the user cares about, e.g. no game or review in
   * progress. The update also waits until the user is not using the page (see `createReloadGate`).
   * It is polled while an update waits, so keep it cheap and free of side effects.
   */
  canReloadNow: () => boolean;
  /** Called once, when the app has been cached for offline use for the first time. */
  onOfflineReady?: () => void;
}

/** Controls the deferred reload onto a new build. */
export interface ReloadGate {
  /** A new build is active: reload as soon as that cannot interrupt the user (maybe right now). */
  request(): void;
  /** True while a reload is waiting. */
  pending(): boolean;
  /** Reloads immediately, ignoring every condition (at most once). */
  reloadNow(): void;
  /** Stops waiting without reloading and removes the listeners; later requests are ignored. */
  dispose(): void;
}

/** The parts of `document` the reload gate uses (a fake one in unit tests). */
export interface ReloadGatePage {
  readonly visibilityState: DocumentVisibilityState;
  addEventListener(type: string, listener: () => void, options?: AddEventListenerOptions): void;
  removeEventListener(type: string, listener: () => void, options?: EventListenerOptions): void;
}

export interface ReloadGateOptions {
  /** How often the conditions are re-checked while a reload waits. */
  pollMs?: number;
  /** The page whose visibility and user input are watched. Default: `document` (none in node). */
  page?: ReloadGatePage;
}

/** How often to look for a new version while the app stays open. */
const UPDATE_CHECK_INTERVAL_MS = 60 * 60 * 1000;
/** Visibility/online update checks closer together than this are skipped. */
const MIN_CHECK_GAP_MS = 60 * 1000;
/** How often the reload conditions are re-checked while an update waits. */
const RELOAD_POLL_MS = 5 * 1000;
/** Input that means the user is using the page: a reload now could lose a tap, a drag or a choice. */
const INPUT_EVENTS = ['pointerdown', 'touchstart', 'keydown'] as const;

let registered = false;

/**
 * Registers the service worker (once) and keeps the app up to date. Call it at startup.
 * Updates are applied by reloading the page (see `createReloadGate` for when).
 */
export function registerServiceWorker(opts: RegisterServiceWorkerOptions): void {
  if (registered || !serviceWorkerSupported()) return;
  registered = true;

  const gate = createReloadGate(opts.canReloadNow, () => window.location.reload());
  let offlineReady = false;
  registerSW({
    immediate: true,
    // In autoUpdate mode this fires once the new service worker controls the page.
    onNeedReload: () => gate.request(),
    // The plugin also reports later updates as "offline ready" when the page started uncontrolled.
    onOfflineReady: () => {
      if (offlineReady) return;
      offlineReady = true;
      opts.onOfflineReady?.();
    },
    onRegisteredSW: (_url, reg) => {
      if (reg) watchForUpdates(reg);
    },
    onRegisterError: (err: unknown) => console.warn('[pwa] service worker registration failed', err),
  });

  // After an update the old build's lazy chunks are gone from both the server and the cache, so a
  // failing dynamic import can only be fixed by loading the new build.
  window.addEventListener('vite:preloadError', () => {
    if (gate.pending()) gate.reloadNow();
  });
}

/**
 * Deferred-reload state machine used by `registerServiceWorker` (exported for tests).
 *
 * Once requested, it reloads when `canReloadNow()` is true and the user cannot be interrupted:
 * - the page is hidden (the app was switched away from or the phone locked), or
 * - the user has not touched the page (pointer, touch or key) since it was loaded or last became
 *   visible, e.g. an update found a few seconds after a launch or a resume.
 * A visible page the user is using is never reloaded: they may be halfway through choosing an
 * opponent. The conditions are re-checked every `pollMs` and on every visibility change.
 */
export function createReloadGate(
  canReloadNow: () => boolean,
  reload: () => void,
  opts: ReloadGateOptions = {},
): ReloadGate {
  const pollMs = opts.pollMs ?? RELOAD_POLL_MS;
  const page: ReloadGatePage | undefined = opts.page ?? (typeof document === 'undefined' ? undefined : document);
  let waiting = false;
  let done = false;
  /** The user has touched the page since it was loaded or last became visible. */
  let touched = false;
  let timer: ReturnType<typeof setInterval> | undefined;

  const inputOptions: AddEventListenerOptions = { capture: true, passive: true };
  const onInput = (): void => {
    touched = true;
  };
  const onVisibilityChange = (): void => {
    if (page?.visibilityState === 'visible') touched = false;
    attempt();
  };
  const stop = (): void => {
    if (timer !== undefined) clearInterval(timer);
    timer = undefined;
    for (const type of INPUT_EVENTS) page?.removeEventListener(type, onInput, inputOptions);
    page?.removeEventListener('visibilitychange', onVisibilityChange);
  };
  const reloadNow = (): void => {
    if (done) return;
    done = true;
    stop();
    reload();
  };
  /** Whether the user may be in the middle of something on the page. */
  const inUse = (): boolean => page !== undefined && page.visibilityState === 'visible' && touched;
  function attempt(): void {
    if (!waiting || done || inUse()) return;
    let ok = false;
    try {
      ok = canReloadNow();
    } catch {
      ok = false;
    }
    if (ok) reloadNow();
  }

  // Input is tracked from the start: an update usually arrives a few seconds after launch, and a
  // tap made before that must still count.
  for (const type of INPUT_EVENTS) page?.addEventListener(type, onInput, inputOptions);
  page?.addEventListener('visibilitychange', onVisibilityChange);

  return {
    request() {
      if (done) return;
      if (!waiting) {
        waiting = true;
        timer = setInterval(attempt, pollMs);
      }
      attempt();
    },
    pending: () => waiting && !done,
    reloadNow,
    dispose() {
      waiting = false;
      done = true;
      stop();
    },
  };
}

function serviceWorkerSupported(): boolean {
  return (
    typeof window !== 'undefined' &&
    typeof navigator !== 'undefined' &&
    'serviceWorker' in navigator &&
    window.isSecureContext !== false
  );
}

/** Polls for a new service worker: hourly, when the app becomes visible, and when back online. */
function watchForUpdates(reg: ServiceWorkerRegistration): void {
  let lastCheck = Date.now(); // registration itself just fetched sw.js
  const check = (force: boolean): void => {
    const now = Date.now();
    if (!force && now - lastCheck < MIN_CHECK_GAP_MS) return;
    if (navigator.onLine === false || reg.installing) return;
    lastCheck = now;
    reg.update().catch(() => {
      /* offline or a server hiccup: the next check retries */
    });
  };
  setInterval(() => check(true), UPDATE_CHECK_INTERVAL_MS);
  document.addEventListener('visibilitychange', () => {
    if (document.visibilityState === 'visible') check(false);
  });
  window.addEventListener('online', () => check(false));
}
